version: 1

deploy:
  steps:
    setupVariables:
      after:
        - echo Replacing !!!NAMESPACE!!! with $NAMESPACE in nested/namespace.yml
        - sed 's/!!!NAMESPACE!!!/'"$NAMESPACE"'/g' nested/namespace.yml > nested/namespace.yml
