version: 1

deploy:
  steps:
    setupVariables:
      after:
        - echo Replacing !!!NAMESPACE!!! with $NAMESPACE in namespace.yml
        - sed 's/!!!NAMESPACE!!!/'"$NAMESPACE"'/g' namespace.yml > namespace.yml
